name: Build and Publish JAR

on:
  push:
    branches:
      - master  # Runs when code is pushed to 'main'
  workflow_dispatch:  # Allows manual triggering

permissions:
  packages: write  # Allows publishing to GitHub Packages
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          server-id: github  # Matches settings.xml
          settings-path: ${{ github.workspace }}  # Location for settings.xml

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          UTILITY_TOKEN: ${{secrets.UTILITY_TOKEN}}  # Authentication
