name: Deploy Framework Utility

on:
  push:
    branches: master # Change to your branch name if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Important: Grants permission to write packages

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19' # Or your Java version
          distribution: 'temurin'

      - name: Build and Deploy with Maven
        run: mvn deploy -s settings.xml # Use settings.xml from the repo
        env:
          UTILITY_TOKEN: ${{secrets.UTILITY_TOKEN}}